sudo: required

services:
  - docker

script:
  - docker build -t quay.io/ukhomeofficedigital/jenkins-aws:travis .
  - docker run -idt --name=travis -p 8080:8080 quay.io/ukhomeofficedigital/jenkins-aws:travis
  - sleep 60 #wait for jenkins to come up
  - curl -w %{http_code} -s --output /dev/null localhost:8080
